; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

	TITLE	c:\Users\EnormousApplePie\Documents\GitHub\Lekmod\LEKMOD_DLL\CvGameCoreDLL_Expansion2\CvDllCivilizationInfo.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
_CIV5_XP2_DLL_VERSION DD FLAT:$SG217164
_DATA	ENDS
CONST	SEGMENT
$SG217164 DB	'1.0.0', 00H
	ORG $+2
_guidICvUnknown DD 0d89ba82fH
	DW	09fa3H
	DW	04696H
	DB	0b3H
	DB	0f4H
	DB	052H
	DB	0bdH
	DB	0b1H
	DB	01H
	DB	0cfH
	DB	0b2H
_guidICvCivilizationInfo1 DD 049c59819H
	DW	0a545H
	DW	04c34H
	DB	093H
	DB	028H
	DB	0caH
	DB	03aH
	DB	0ceH
	DB	0d9H
	DB	032H
	DB	0b8H
CONST	ENDS
PUBLIC	??_7ICvUnknown@@6B@				; ICvUnknown::`vftable'
PUBLIC	??0ICvUnknown@@QAE@XZ				; ICvUnknown::ICvUnknown
PUBLIC	??_R4ICvUnknown@@6B@				; ICvUnknown::`RTTI Complete Object Locator'
PUBLIC	??_R0?AVICvUnknown@@@8				; ICvUnknown `RTTI Type Descriptor'
PUBLIC	??_R3ICvUnknown@@8				; ICvUnknown::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2ICvUnknown@@8				; ICvUnknown::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@ICvUnknown@@8			; ICvUnknown::`RTTI Base Class Descriptor at (0,-1,0,64)'
EXTRN	??_7type_info@@6B@:QWORD			; type_info::`vftable'
EXTRN	__purecall:PROC
;	COMDAT ??_R1A@?0A@EA@ICvUnknown@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@ICvUnknown@@8 DD FLAT:??_R0?AVICvUnknown@@@8 ; ICvUnknown::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	00H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3ICvUnknown@@8
rdata$r	ENDS
;	COMDAT ??_R2ICvUnknown@@8
rdata$r	SEGMENT
??_R2ICvUnknown@@8 DD FLAT:??_R1A@?0A@EA@ICvUnknown@@8	; ICvUnknown::`RTTI Base Class Array'
rdata$r	ENDS
;	COMDAT ??_R3ICvUnknown@@8
rdata$r	SEGMENT
??_R3ICvUnknown@@8 DD 00H				; ICvUnknown::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	01H
	DD	FLAT:??_R2ICvUnknown@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVICvUnknown@@@8
_DATA	SEGMENT
??_R0?AVICvUnknown@@@8 DD FLAT:??_7type_info@@6B@	; ICvUnknown `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVICvUnknown@@', 00H
_DATA	ENDS
;	COMDAT ??_R4ICvUnknown@@6B@
rdata$r	SEGMENT
??_R4ICvUnknown@@6B@ DD 00H				; ICvUnknown::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	FLAT:??_R0?AVICvUnknown@@@8
	DD	FLAT:??_R3ICvUnknown@@8
rdata$r	ENDS
;	COMDAT ??_7ICvUnknown@@6B@
CONST	SEGMENT
??_7ICvUnknown@@6B@ DD FLAT:??_R4ICvUnknown@@6B@	; ICvUnknown::`vftable'
	DD	FLAT:__purecall
	DD	FLAT:__purecall
; Function compile flags: /Ogtpy
CONST	ENDS
;	COMDAT ??0ICvUnknown@@QAE@XZ
_TEXT	SEGMENT
??0ICvUnknown@@QAE@XZ PROC				; ICvUnknown::ICvUnknown, COMDAT
; _this$ = ecx
	mov	eax, ecx
	mov	DWORD PTR [eax], OFFSET ??_7ICvUnknown@@6B@
	ret	0
??0ICvUnknown@@QAE@XZ ENDP				; ICvUnknown::ICvUnknown
_TEXT	ENDS
PUBLIC	??_7CvDllCivilizationInfo@@6B@			; CvDllCivilizationInfo::`vftable'
PUBLIC	??1CvDllCivilizationInfo@@QAE@XZ		; CvDllCivilizationInfo::~CvDllCivilizationInfo
PUBLIC	??_R4CvDllCivilizationInfo@@6B@			; CvDllCivilizationInfo::`RTTI Complete Object Locator'
PUBLIC	??_R0?AVCvDllCivilizationInfo@@@8		; CvDllCivilizationInfo `RTTI Type Descriptor'
PUBLIC	??_R3CvDllCivilizationInfo@@8			; CvDllCivilizationInfo::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2CvDllCivilizationInfo@@8			; CvDllCivilizationInfo::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@CvDllCivilizationInfo@@8		; CvDllCivilizationInfo::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R1A@?0A@EA@ICvCivilizationInfo1@@8		; ICvCivilizationInfo1::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R0?AVICvCivilizationInfo1@@@8		; ICvCivilizationInfo1 `RTTI Type Descriptor'
PUBLIC	??_R3ICvCivilizationInfo1@@8			; ICvCivilizationInfo1::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2ICvCivilizationInfo1@@8			; ICvCivilizationInfo1::`RTTI Base Class Array'
PUBLIC	?QueryInterface@CvDllCivilizationInfo@@UAGPAXU_GUID@@@Z ; CvDllCivilizationInfo::QueryInterface
PUBLIC	?Destroy@CvDllCivilizationInfo@@EAGXXZ		; CvDllCivilizationInfo::Destroy
PUBLIC	?GetType@CvDllCivilizationInfo@@UAGPBDXZ	; CvDllCivilizationInfo::GetType
PUBLIC	?GetDescription@CvDllCivilizationInfo@@UAGPBDXZ	; CvDllCivilizationInfo::GetDescription
PUBLIC	?IsAIPlayable@CvDllCivilizationInfo@@UAG_NXZ	; CvDllCivilizationInfo::IsAIPlayable
PUBLIC	?IsPlayable@CvDllCivilizationInfo@@UAG_NXZ	; CvDllCivilizationInfo::IsPlayable
PUBLIC	?GetShortDescription@CvDllCivilizationInfo@@UAGPBDXZ ; CvDllCivilizationInfo::GetShortDescription
PUBLIC	?GetDefaultPlayerColor@CvDllCivilizationInfo@@UAGHXZ ; CvDllCivilizationInfo::GetDefaultPlayerColor
PUBLIC	?GetArtStyleType@CvDllCivilizationInfo@@UAGHXZ	; CvDllCivilizationInfo::GetArtStyleType
PUBLIC	?GetNumCityNames@CvDllCivilizationInfo@@UAGHXZ	; CvDllCivilizationInfo::GetNumCityNames
PUBLIC	?GetArtStylePrefix@CvDllCivilizationInfo@@UAGPBDXZ ; CvDllCivilizationInfo::GetArtStylePrefix
PUBLIC	?GetArtStyleSuffix@CvDllCivilizationInfo@@UAGPBDXZ ; CvDllCivilizationInfo::GetArtStyleSuffix
PUBLIC	?GetDawnOfManAudio@CvDllCivilizationInfo@@UAGPBDXZ ; CvDllCivilizationInfo::GetDawnOfManAudio
PUBLIC	?GetCivilizationBuildings@CvDllCivilizationInfo@@UAGHH@Z ; CvDllCivilizationInfo::GetCivilizationBuildings
PUBLIC	?IsLeaders@CvDllCivilizationInfo@@UAG_NH@Z	; CvDllCivilizationInfo::IsLeaders
PUBLIC	?GetCityNames@CvDllCivilizationInfo@@UAGPBDH@Z	; CvDllCivilizationInfo::GetCityNames
PUBLIC	?GetSoundtrackKey@CvDllCivilizationInfo@@UAGPBDXZ ; CvDllCivilizationInfo::GetSoundtrackKey
;	COMDAT ??_R2ICvCivilizationInfo1@@8
; File c:\users\enormousapplepie\documents\github\lekmod\lekmod_dll\cvgamecoredll_expansion2\cvdllcivilizationinfo.cpp
rdata$r	SEGMENT
??_R2ICvCivilizationInfo1@@8 DD FLAT:??_R1A@?0A@EA@ICvCivilizationInfo1@@8 ; ICvCivilizationInfo1::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@ICvUnknown@@8
rdata$r	ENDS
;	COMDAT ??_R3ICvCivilizationInfo1@@8
rdata$r	SEGMENT
??_R3ICvCivilizationInfo1@@8 DD 00H			; ICvCivilizationInfo1::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	02H
	DD	FLAT:??_R2ICvCivilizationInfo1@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVICvCivilizationInfo1@@@8
_DATA	SEGMENT
??_R0?AVICvCivilizationInfo1@@@8 DD FLAT:??_7type_info@@6B@ ; ICvCivilizationInfo1 `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVICvCivilizationInfo1@@', 00H
_DATA	ENDS
;	COMDAT ??_R1A@?0A@EA@ICvCivilizationInfo1@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@ICvCivilizationInfo1@@8 DD FLAT:??_R0?AVICvCivilizationInfo1@@@8 ; ICvCivilizationInfo1::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	01H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3ICvCivilizationInfo1@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@CvDllCivilizationInfo@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CvDllCivilizationInfo@@8 DD FLAT:??_R0?AVCvDllCivilizationInfo@@@8 ; CvDllCivilizationInfo::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	02H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CvDllCivilizationInfo@@8
rdata$r	ENDS
;	COMDAT ??_R2CvDllCivilizationInfo@@8
rdata$r	SEGMENT
??_R2CvDllCivilizationInfo@@8 DD FLAT:??_R1A@?0A@EA@CvDllCivilizationInfo@@8 ; CvDllCivilizationInfo::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@ICvCivilizationInfo1@@8
	DD	FLAT:??_R1A@?0A@EA@ICvUnknown@@8
rdata$r	ENDS
;	COMDAT ??_R3CvDllCivilizationInfo@@8
rdata$r	SEGMENT
??_R3CvDllCivilizationInfo@@8 DD 00H			; CvDllCivilizationInfo::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	03H
	DD	FLAT:??_R2CvDllCivilizationInfo@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCvDllCivilizationInfo@@@8
_DATA	SEGMENT
??_R0?AVCvDllCivilizationInfo@@@8 DD FLAT:??_7type_info@@6B@ ; CvDllCivilizationInfo `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCvDllCivilizationInfo@@', 00H
_DATA	ENDS
;	COMDAT ??_R4CvDllCivilizationInfo@@6B@
rdata$r	SEGMENT
??_R4CvDllCivilizationInfo@@6B@ DD 00H			; CvDllCivilizationInfo::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	FLAT:??_R0?AVCvDllCivilizationInfo@@@8
	DD	FLAT:??_R3CvDllCivilizationInfo@@8
rdata$r	ENDS
;	COMDAT ??_7CvDllCivilizationInfo@@6B@
CONST	SEGMENT
??_7CvDllCivilizationInfo@@6B@ DD FLAT:??_R4CvDllCivilizationInfo@@6B@ ; CvDllCivilizationInfo::`vftable'
	DD	FLAT:?QueryInterface@CvDllCivilizationInfo@@UAGPAXU_GUID@@@Z
	DD	FLAT:?Destroy@CvDllCivilizationInfo@@EAGXXZ
	DD	FLAT:?GetType@CvDllCivilizationInfo@@UAGPBDXZ
	DD	FLAT:?GetDescription@CvDllCivilizationInfo@@UAGPBDXZ
	DD	FLAT:?IsAIPlayable@CvDllCivilizationInfo@@UAG_NXZ
	DD	FLAT:?IsPlayable@CvDllCivilizationInfo@@UAG_NXZ
	DD	FLAT:?GetShortDescription@CvDllCivilizationInfo@@UAGPBDXZ
	DD	FLAT:?GetDefaultPlayerColor@CvDllCivilizationInfo@@UAGHXZ
	DD	FLAT:?GetArtStyleType@CvDllCivilizationInfo@@UAGHXZ
	DD	FLAT:?GetNumCityNames@CvDllCivilizationInfo@@UAGHXZ
	DD	FLAT:?GetArtStylePrefix@CvDllCivilizationInfo@@UAGPBDXZ
	DD	FLAT:?GetArtStyleSuffix@CvDllCivilizationInfo@@UAGPBDXZ
	DD	FLAT:?GetDawnOfManAudio@CvDllCivilizationInfo@@UAGPBDXZ
	DD	FLAT:?GetCivilizationBuildings@CvDllCivilizationInfo@@UAGHH@Z
	DD	FLAT:?IsLeaders@CvDllCivilizationInfo@@UAG_NH@Z
	DD	FLAT:?GetCityNames@CvDllCivilizationInfo@@UAGPBDH@Z
	DD	FLAT:?GetSoundtrackKey@CvDllCivilizationInfo@@UAGPBDXZ
; Function compile flags: /Ogtpy
CONST	ENDS
;	COMDAT ??1CvDllCivilizationInfo@@QAE@XZ
_TEXT	SEGMENT
??1CvDllCivilizationInfo@@QAE@XZ PROC			; CvDllCivilizationInfo::~CvDllCivilizationInfo, COMDAT
; _this$ = ecx

; 24   : {

	mov	DWORD PTR [ecx], OFFSET ??_7CvDllCivilizationInfo@@6B@

; 25   : }

	ret	0
??1CvDllCivilizationInfo@@QAE@XZ ENDP			; CvDllCivilizationInfo::~CvDllCivilizationInfo
_TEXT	ENDS
PUBLIC	?IncrementReference@CvDllCivilizationInfo@@QAEIXZ ; CvDllCivilizationInfo::IncrementReference
; Function compile flags: /Ogtpy
;	COMDAT ?IncrementReference@CvDllCivilizationInfo@@QAEIXZ
_TEXT	SEGMENT
?IncrementReference@CvDllCivilizationInfo@@QAEIXZ PROC	; CvDllCivilizationInfo::IncrementReference, COMDAT
; _this$ = ecx

; 41   : 	++m_uiRefCount;

	inc	DWORD PTR [ecx+4]

; 42   : 	return m_uiRefCount;

	mov	eax, DWORD PTR [ecx+4]

; 43   : }

	ret	0
?IncrementReference@CvDllCivilizationInfo@@QAEIXZ ENDP	; CvDllCivilizationInfo::IncrementReference
_TEXT	ENDS
PUBLIC	?GetReferenceCount@CvDllCivilizationInfo@@QAEIXZ ; CvDllCivilizationInfo::GetReferenceCount
; Function compile flags: /Ogtpy
;	COMDAT ?GetReferenceCount@CvDllCivilizationInfo@@QAEIXZ
_TEXT	SEGMENT
?GetReferenceCount@CvDllCivilizationInfo@@QAEIXZ PROC	; CvDllCivilizationInfo::GetReferenceCount, COMDAT
; _this$ = ecx

; 61   : 	return m_uiRefCount;

	mov	eax, DWORD PTR [ecx+4]

; 62   : }

	ret	0
?GetReferenceCount@CvDllCivilizationInfo@@QAEIXZ ENDP	; CvDllCivilizationInfo::GetReferenceCount
_TEXT	ENDS
PUBLIC	??3CvDllCivilizationInfo@@SAXPAX@Z		; CvDllCivilizationInfo::operator delete
EXTRN	?Free@CvDllGameContext@@SAXPAX@Z:PROC		; CvDllGameContext::Free
; Function compile flags: /Ogtpy
;	COMDAT ??3CvDllCivilizationInfo@@SAXPAX@Z
_TEXT	SEGMENT
_p$ = 8							; size = 4
??3CvDllCivilizationInfo@@SAXPAX@Z PROC			; CvDllCivilizationInfo::operator delete, COMDAT

; 71   : 	CvDllGameContext::Free(p);

	jmp	?Free@CvDllGameContext@@SAXPAX@Z	; CvDllGameContext::Free
??3CvDllCivilizationInfo@@SAXPAX@Z ENDP			; CvDllCivilizationInfo::operator delete
_TEXT	ENDS
PUBLIC	??2CvDllCivilizationInfo@@SAPAXI@Z		; CvDllCivilizationInfo::operator new
EXTRN	?Allocate@CvDllGameContext@@SAPAXI@Z:PROC	; CvDllGameContext::Allocate
; Function compile flags: /Ogtpy
;	COMDAT ??2CvDllCivilizationInfo@@SAPAXI@Z
_TEXT	SEGMENT
_bytes$ = 8						; size = 4
??2CvDllCivilizationInfo@@SAPAXI@Z PROC			; CvDllCivilizationInfo::operator new, COMDAT

; 76   : 	return CvDllGameContext::Allocate(bytes);

	jmp	?Allocate@CvDllGameContext@@SAPAXI@Z	; CvDllGameContext::Allocate
??2CvDllCivilizationInfo@@SAPAXI@Z ENDP			; CvDllCivilizationInfo::operator new
_TEXT	ENDS
PUBLIC	?GetInstance@CvDllCivilizationInfo@@QAEPAVCvCivilizationInfo@@XZ ; CvDllCivilizationInfo::GetInstance
; Function compile flags: /Ogtpy
;	COMDAT ?GetInstance@CvDllCivilizationInfo@@QAEPAVCvCivilizationInfo@@XZ
_TEXT	SEGMENT
?GetInstance@CvDllCivilizationInfo@@QAEPAVCvCivilizationInfo@@XZ PROC ; CvDllCivilizationInfo::GetInstance, COMDAT
; _this$ = ecx

; 81   : 	return m_pCivilizationInfo;

	mov	eax, DWORD PTR [ecx+8]

; 82   : }

	ret	0
?GetInstance@CvDllCivilizationInfo@@QAEPAVCvCivilizationInfo@@XZ ENDP ; CvDllCivilizationInfo::GetInstance
_TEXT	ENDS
EXTRN	?isAIPlayable@CvCivilizationBaseInfo@@QBE_NXZ:PROC ; CvCivilizationBaseInfo::isAIPlayable
; Function compile flags: /Ogtpy
;	COMDAT ?IsAIPlayable@CvDllCivilizationInfo@@UAG_NXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?IsAIPlayable@CvDllCivilizationInfo@@UAG_NXZ PROC	; CvDllCivilizationInfo::IsAIPlayable, COMDAT

; 96   : 	return m_pCivilizationInfo->isAIPlayable();

	mov	eax, DWORD PTR _this$[esp-4]
	mov	ecx, DWORD PTR [eax+8]
	call	?isAIPlayable@CvCivilizationBaseInfo@@QBE_NXZ ; CvCivilizationBaseInfo::isAIPlayable

; 97   : }

	ret	4
?IsAIPlayable@CvDllCivilizationInfo@@UAG_NXZ ENDP	; CvDllCivilizationInfo::IsAIPlayable
_TEXT	ENDS
EXTRN	?isPlayable@CvCivilizationBaseInfo@@QBE_NXZ:PROC ; CvCivilizationBaseInfo::isPlayable
; Function compile flags: /Ogtpy
;	COMDAT ?IsPlayable@CvDllCivilizationInfo@@UAG_NXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?IsPlayable@CvDllCivilizationInfo@@UAG_NXZ PROC		; CvDllCivilizationInfo::IsPlayable, COMDAT

; 101  : 	return m_pCivilizationInfo->isPlayable();

	mov	eax, DWORD PTR _this$[esp-4]
	mov	ecx, DWORD PTR [eax+8]
	call	?isPlayable@CvCivilizationBaseInfo@@QBE_NXZ ; CvCivilizationBaseInfo::isPlayable

; 102  : }

	ret	4
?IsPlayable@CvDllCivilizationInfo@@UAG_NXZ ENDP		; CvDllCivilizationInfo::IsPlayable
_TEXT	ENDS
EXTRN	?getShortDescription@CvCivilizationBaseInfo@@QBEPBDXZ:PROC ; CvCivilizationBaseInfo::getShortDescription
; Function compile flags: /Ogtpy
;	COMDAT ?GetShortDescription@CvDllCivilizationInfo@@UAGPBDXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetShortDescription@CvDllCivilizationInfo@@UAGPBDXZ PROC ; CvDllCivilizationInfo::GetShortDescription, COMDAT

; 106  : 	return m_pCivilizationInfo->getShortDescription();

	mov	eax, DWORD PTR _this$[esp-4]
	mov	ecx, DWORD PTR [eax+8]
	call	?getShortDescription@CvCivilizationBaseInfo@@QBEPBDXZ ; CvCivilizationBaseInfo::getShortDescription

; 107  : }

	ret	4
?GetShortDescription@CvDllCivilizationInfo@@UAGPBDXZ ENDP ; CvDllCivilizationInfo::GetShortDescription
_TEXT	ENDS
EXTRN	?getDefaultPlayerColor@CvCivilizationInfo@@QBEHXZ:PROC ; CvCivilizationInfo::getDefaultPlayerColor
; Function compile flags: /Ogtpy
;	COMDAT ?GetDefaultPlayerColor@CvDllCivilizationInfo@@UAGHXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetDefaultPlayerColor@CvDllCivilizationInfo@@UAGHXZ PROC ; CvDllCivilizationInfo::GetDefaultPlayerColor, COMDAT

; 111  : 	return m_pCivilizationInfo->getDefaultPlayerColor();

	mov	eax, DWORD PTR _this$[esp-4]
	mov	ecx, DWORD PTR [eax+8]
	call	?getDefaultPlayerColor@CvCivilizationInfo@@QBEHXZ ; CvCivilizationInfo::getDefaultPlayerColor

; 112  : }

	ret	4
?GetDefaultPlayerColor@CvDllCivilizationInfo@@UAGHXZ ENDP ; CvDllCivilizationInfo::GetDefaultPlayerColor
_TEXT	ENDS
EXTRN	?getArtStyleType@CvCivilizationInfo@@QBEHXZ:PROC ; CvCivilizationInfo::getArtStyleType
; Function compile flags: /Ogtpy
;	COMDAT ?GetArtStyleType@CvDllCivilizationInfo@@UAGHXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetArtStyleType@CvDllCivilizationInfo@@UAGHXZ PROC	; CvDllCivilizationInfo::GetArtStyleType, COMDAT

; 116  : 	return m_pCivilizationInfo->getArtStyleType();

	mov	eax, DWORD PTR _this$[esp-4]
	mov	ecx, DWORD PTR [eax+8]
	call	?getArtStyleType@CvCivilizationInfo@@QBEHXZ ; CvCivilizationInfo::getArtStyleType

; 117  : }

	ret	4
?GetArtStyleType@CvDllCivilizationInfo@@UAGHXZ ENDP	; CvDllCivilizationInfo::GetArtStyleType
_TEXT	ENDS
EXTRN	?getNumCityNames@CvCivilizationInfo@@QBEHXZ:PROC ; CvCivilizationInfo::getNumCityNames
; Function compile flags: /Ogtpy
;	COMDAT ?GetNumCityNames@CvDllCivilizationInfo@@UAGHXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetNumCityNames@CvDllCivilizationInfo@@UAGHXZ PROC	; CvDllCivilizationInfo::GetNumCityNames, COMDAT

; 121  : 	return m_pCivilizationInfo->getNumCityNames();

	mov	eax, DWORD PTR _this$[esp-4]
	mov	ecx, DWORD PTR [eax+8]
	call	?getNumCityNames@CvCivilizationInfo@@QBEHXZ ; CvCivilizationInfo::getNumCityNames

; 122  : }

	ret	4
?GetNumCityNames@CvDllCivilizationInfo@@UAGHXZ ENDP	; CvDllCivilizationInfo::GetNumCityNames
_TEXT	ENDS
EXTRN	?getArtStylePrefix@CvCivilizationInfo@@QBEPBDXZ:PROC ; CvCivilizationInfo::getArtStylePrefix
; Function compile flags: /Ogtpy
;	COMDAT ?GetArtStylePrefix@CvDllCivilizationInfo@@UAGPBDXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetArtStylePrefix@CvDllCivilizationInfo@@UAGPBDXZ PROC	; CvDllCivilizationInfo::GetArtStylePrefix, COMDAT

; 126  : 	return m_pCivilizationInfo->getArtStylePrefix();

	mov	eax, DWORD PTR _this$[esp-4]
	mov	ecx, DWORD PTR [eax+8]
	call	?getArtStylePrefix@CvCivilizationInfo@@QBEPBDXZ ; CvCivilizationInfo::getArtStylePrefix

; 127  : }

	ret	4
?GetArtStylePrefix@CvDllCivilizationInfo@@UAGPBDXZ ENDP	; CvDllCivilizationInfo::GetArtStylePrefix
_TEXT	ENDS
EXTRN	?getArtStyleSuffix@CvCivilizationInfo@@QBEPBDXZ:PROC ; CvCivilizationInfo::getArtStyleSuffix
; Function compile flags: /Ogtpy
;	COMDAT ?GetArtStyleSuffix@CvDllCivilizationInfo@@UAGPBDXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetArtStyleSuffix@CvDllCivilizationInfo@@UAGPBDXZ PROC	; CvDllCivilizationInfo::GetArtStyleSuffix, COMDAT

; 131  : 	return m_pCivilizationInfo->getArtStyleSuffix();

	mov	eax, DWORD PTR _this$[esp-4]
	mov	ecx, DWORD PTR [eax+8]
	call	?getArtStyleSuffix@CvCivilizationInfo@@QBEPBDXZ ; CvCivilizationInfo::getArtStyleSuffix

; 132  : }

	ret	4
?GetArtStyleSuffix@CvDllCivilizationInfo@@UAGPBDXZ ENDP	; CvDllCivilizationInfo::GetArtStyleSuffix
_TEXT	ENDS
EXTRN	?GetDawnOfManAudio@CvCivilizationInfo@@QBEPBDXZ:PROC ; CvCivilizationInfo::GetDawnOfManAudio
; Function compile flags: /Ogtpy
;	COMDAT ?GetDawnOfManAudio@CvDllCivilizationInfo@@UAGPBDXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetDawnOfManAudio@CvDllCivilizationInfo@@UAGPBDXZ PROC	; CvDllCivilizationInfo::GetDawnOfManAudio, COMDAT

; 136  : 	return m_pCivilizationInfo->GetDawnOfManAudio();

	mov	eax, DWORD PTR _this$[esp-4]
	mov	ecx, DWORD PTR [eax+8]
	call	?GetDawnOfManAudio@CvCivilizationInfo@@QBEPBDXZ ; CvCivilizationInfo::GetDawnOfManAudio

; 137  : }

	ret	4
?GetDawnOfManAudio@CvDllCivilizationInfo@@UAGPBDXZ ENDP	; CvDllCivilizationInfo::GetDawnOfManAudio
_TEXT	ENDS
EXTRN	?getCivilizationBuildings@CvCivilizationInfo@@QBEHH@Z:PROC ; CvCivilizationInfo::getCivilizationBuildings
; Function compile flags: /Ogtpy
;	COMDAT ?GetCivilizationBuildings@CvDllCivilizationInfo@@UAGHH@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_i$ = 12						; size = 4
?GetCivilizationBuildings@CvDllCivilizationInfo@@UAGHH@Z PROC ; CvDllCivilizationInfo::GetCivilizationBuildings, COMDAT

; 141  : 	return m_pCivilizationInfo->getCivilizationBuildings(i);

	mov	eax, DWORD PTR _i$[esp-4]
	mov	ecx, DWORD PTR _this$[esp-4]
	mov	ecx, DWORD PTR [ecx+8]
	push	eax
	call	?getCivilizationBuildings@CvCivilizationInfo@@QBEHH@Z ; CvCivilizationInfo::getCivilizationBuildings

; 142  : }

	ret	8
?GetCivilizationBuildings@CvDllCivilizationInfo@@UAGHH@Z ENDP ; CvDllCivilizationInfo::GetCivilizationBuildings
_TEXT	ENDS
EXTRN	?isLeaders@CvCivilizationInfo@@QBE_NH@Z:PROC	; CvCivilizationInfo::isLeaders
; Function compile flags: /Ogtpy
;	COMDAT ?IsLeaders@CvDllCivilizationInfo@@UAG_NH@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_i$ = 12						; size = 4
?IsLeaders@CvDllCivilizationInfo@@UAG_NH@Z PROC		; CvDllCivilizationInfo::IsLeaders, COMDAT

; 146  : 	return m_pCivilizationInfo->isLeaders(i);

	mov	eax, DWORD PTR _i$[esp-4]
	mov	ecx, DWORD PTR _this$[esp-4]
	mov	ecx, DWORD PTR [ecx+8]
	push	eax
	call	?isLeaders@CvCivilizationInfo@@QBE_NH@Z	; CvCivilizationInfo::isLeaders

; 147  : }

	ret	8
?IsLeaders@CvDllCivilizationInfo@@UAG_NH@Z ENDP		; CvDllCivilizationInfo::IsLeaders
_TEXT	ENDS
EXTRN	?getCityNames@CvCivilizationInfo@@QBEPBDH@Z:PROC ; CvCivilizationInfo::getCityNames
; Function compile flags: /Ogtpy
;	COMDAT ?GetCityNames@CvDllCivilizationInfo@@UAGPBDH@Z
_TEXT	SEGMENT
_this$ = 8						; size = 4
_i$ = 12						; size = 4
?GetCityNames@CvDllCivilizationInfo@@UAGPBDH@Z PROC	; CvDllCivilizationInfo::GetCityNames, COMDAT

; 151  : 	return m_pCivilizationInfo->getCityNames(i);

	mov	eax, DWORD PTR _i$[esp-4]
	mov	ecx, DWORD PTR _this$[esp-4]
	mov	ecx, DWORD PTR [ecx+8]
	push	eax
	call	?getCityNames@CvCivilizationInfo@@QBEPBDH@Z ; CvCivilizationInfo::getCityNames

; 152  : }

	ret	8
?GetCityNames@CvDllCivilizationInfo@@UAGPBDH@Z ENDP	; CvDllCivilizationInfo::GetCityNames
_TEXT	ENDS
EXTRN	?getSoundtrackKey@CvCivilizationInfo@@QBEPBDXZ:PROC ; CvCivilizationInfo::getSoundtrackKey
; Function compile flags: /Ogtpy
;	COMDAT ?GetSoundtrackKey@CvDllCivilizationInfo@@UAGPBDXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetSoundtrackKey@CvDllCivilizationInfo@@UAGPBDXZ PROC	; CvDllCivilizationInfo::GetSoundtrackKey, COMDAT

; 156  : 	return m_pCivilizationInfo->getSoundtrackKey();

	mov	eax, DWORD PTR _this$[esp-4]
	mov	ecx, DWORD PTR [eax+8]
	call	?getSoundtrackKey@CvCivilizationInfo@@QBEPBDXZ ; CvCivilizationInfo::getSoundtrackKey

; 157  : }

	ret	4
?GetSoundtrackKey@CvDllCivilizationInfo@@UAGPBDXZ ENDP	; CvDllCivilizationInfo::GetSoundtrackKey
_TEXT	ENDS
PUBLIC	_IsEqualGUID
; Function compile flags: /Ogtpy
; File c:\program files\microsoft sdks\windows\v6.0a\include\guiddef.h
;	COMDAT _IsEqualGUID
_TEXT	SEGMENT
_rguid1$ = 8						; size = 4
_rguid2$ = 12						; size = 4
_IsEqualGUID PROC					; COMDAT

; 161  :     return !memcmp(&rguid1, &rguid2, sizeof(GUID));

	mov	ecx, DWORD PTR _rguid2$[esp-4]
	mov	edx, DWORD PTR _rguid1$[esp-4]
	mov	eax, 16					; 00000010H
	push	esi
	npad	2
$LL4@IsEqualGUI:
	mov	esi, DWORD PTR [edx]
	cmp	esi, DWORD PTR [ecx]
	jne	SHORT $LN5@IsEqualGUI
	sub	eax, 4
	add	ecx, 4
	add	edx, 4
	cmp	eax, 4
	jae	SHORT $LL4@IsEqualGUI
	xor	eax, eax
	xor	edx, edx
	test	eax, eax
	sete	dl
	pop	esi
	mov	eax, edx

; 162  : }

	ret	0
$LN5@IsEqualGUI:

; 161  :     return !memcmp(&rguid1, &rguid2, sizeof(GUID));

	movzx	eax, BYTE PTR [edx]
	movzx	esi, BYTE PTR [ecx]
	sub	eax, esi
	jne	SHORT $LN7@IsEqualGUI
	movzx	eax, BYTE PTR [edx+1]
	movzx	esi, BYTE PTR [ecx+1]
	sub	eax, esi
	jne	SHORT $LN7@IsEqualGUI
	movzx	eax, BYTE PTR [edx+2]
	movzx	esi, BYTE PTR [ecx+2]
	sub	eax, esi
	jne	SHORT $LN7@IsEqualGUI
	movzx	eax, BYTE PTR [edx+3]
	movzx	ecx, BYTE PTR [ecx+3]
	sub	eax, ecx
$LN7@IsEqualGUI:
	sar	eax, 31					; 0000001fH
	or	eax, 1
	xor	edx, edx
	test	eax, eax
	sete	dl
	pop	esi
	mov	eax, edx

; 162  : }

	ret	0
_IsEqualGUID ENDP
_TEXT	ENDS
PUBLIC	_==
; Function compile flags: /Ogtpy
;	COMDAT _==
_TEXT	SEGMENT
_guidOne$ = 8						; size = 4
_guidOther$ = 12					; size = 4
_==	PROC						; COMDAT

; 194  :     return IsEqualGUID(guidOne,guidOther);

	jmp	_IsEqualGUID
_==	ENDP
_TEXT	ENDS
PUBLIC	?GetInterfaceId@ICvUnknown@@SG?AU_GUID@@XZ	; ICvUnknown::GetInterfaceId
; Function compile flags: /Ogtpy
; File c:\users\enormousapplepie\documents\github\lekmod\lekmod_dll\cvgamecoredllutil\include\cvdllinterfaces.h
;	COMDAT ?GetInterfaceId@ICvUnknown@@SG?AU_GUID@@XZ
_TEXT	SEGMENT
$T218588 = 8						; size = 4
?GetInterfaceId@ICvUnknown@@SG?AU_GUID@@XZ PROC		; ICvUnknown::GetInterfaceId, COMDAT

; 306  : 	static GUID DLLCALL GetInterfaceId(){ return guidICvUnknown; }

	mov	eax, DWORD PTR $T218588[esp-4]
	mov	ecx, DWORD PTR _guidICvUnknown
	mov	edx, DWORD PTR _guidICvUnknown+4
	mov	DWORD PTR [eax], ecx
	mov	ecx, DWORD PTR _guidICvUnknown+8
	mov	DWORD PTR [eax+4], edx
	mov	edx, DWORD PTR _guidICvUnknown+12
	mov	DWORD PTR [eax+8], ecx
	mov	DWORD PTR [eax+12], edx
	ret	4
?GetInterfaceId@ICvUnknown@@SG?AU_GUID@@XZ ENDP		; ICvUnknown::GetInterfaceId
_TEXT	ENDS
PUBLIC	?GetInterfaceId@ICvCivilizationInfo1@@SG?AU_GUID@@XZ ; ICvCivilizationInfo1::GetInterfaceId
; Function compile flags: /Ogtpy
;	COMDAT ?GetInterfaceId@ICvCivilizationInfo1@@SG?AU_GUID@@XZ
_TEXT	SEGMENT
$T218592 = 8						; size = 4
?GetInterfaceId@ICvCivilizationInfo1@@SG?AU_GUID@@XZ PROC ; ICvCivilizationInfo1::GetInterfaceId, COMDAT

; 353  : 	static GUID DLLCALL GetInterfaceId() { return guidICvCivilizationInfo1; }

	mov	eax, DWORD PTR $T218592[esp-4]
	mov	ecx, DWORD PTR _guidICvCivilizationInfo1
	mov	edx, DWORD PTR _guidICvCivilizationInfo1+4
	mov	DWORD PTR [eax], ecx
	mov	ecx, DWORD PTR _guidICvCivilizationInfo1+8
	mov	DWORD PTR [eax+4], edx
	mov	edx, DWORD PTR _guidICvCivilizationInfo1+12
	mov	DWORD PTR [eax+8], ecx
	mov	DWORD PTR [eax+12], edx
	ret	4
?GetInterfaceId@ICvCivilizationInfo1@@SG?AU_GUID@@XZ ENDP ; ICvCivilizationInfo1::GetInterfaceId
_TEXT	ENDS
PUBLIC	?GetDescription@CvBaseInfo@@QBEPBDXZ		; CvBaseInfo::GetDescription
EXTRN	__imp_?c_str@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QBEPBDXZ:PROC
; Function compile flags: /Ogtpy
; File c:\users\enormousapplepie\documents\github\lekmod\lekmod_dll\cvgamecoredll_expansion2\cvinfos.h
;	COMDAT ?GetDescription@CvBaseInfo@@QBEPBDXZ
_TEXT	SEGMENT
?GetDescription@CvBaseInfo@@QBEPBDXZ PROC		; CvBaseInfo::GetDescription, COMDAT
; _this$ = ecx

; 64   : 		return m_strDescription.c_str();

	add	ecx, 36					; 00000024H
	jmp	DWORD PTR __imp_?c_str@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QBEPBDXZ
?GetDescription@CvBaseInfo@@QBEPBDXZ ENDP		; CvBaseInfo::GetDescription
_TEXT	ENDS
PUBLIC	?GetType@CvBaseInfo@@QBEPBDXZ			; CvBaseInfo::GetType
; Function compile flags: /Ogtpy
;	COMDAT ?GetType@CvBaseInfo@@QBEPBDXZ
_TEXT	SEGMENT
?GetType@CvBaseInfo@@QBEPBDXZ PROC			; CvBaseInfo::GetType, COMDAT
; _this$ = ecx

; 92   : 		return m_strType.c_str();

	add	ecx, 176				; 000000b0H
	jmp	DWORD PTR __imp_?c_str@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QBEPBDXZ
?GetType@CvBaseInfo@@QBEPBDXZ ENDP			; CvBaseInfo::GetType
_TEXT	ENDS
PUBLIC	??_7ICvCivilizationInfo1@@6B@			; ICvCivilizationInfo1::`vftable'
PUBLIC	??0ICvCivilizationInfo1@@QAE@XZ			; ICvCivilizationInfo1::ICvCivilizationInfo1
PUBLIC	??_R4ICvCivilizationInfo1@@6B@			; ICvCivilizationInfo1::`RTTI Complete Object Locator'
;	COMDAT ??_R4ICvCivilizationInfo1@@6B@
rdata$r	SEGMENT
??_R4ICvCivilizationInfo1@@6B@ DD 00H			; ICvCivilizationInfo1::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	FLAT:??_R0?AVICvCivilizationInfo1@@@8
	DD	FLAT:??_R3ICvCivilizationInfo1@@8
rdata$r	ENDS
;	COMDAT ??_7ICvCivilizationInfo1@@6B@
CONST	SEGMENT
??_7ICvCivilizationInfo1@@6B@ DD FLAT:??_R4ICvCivilizationInfo1@@6B@ ; ICvCivilizationInfo1::`vftable'
	DD	FLAT:__purecall
	DD	FLAT:__purecall
	DD	FLAT:__purecall
	DD	FLAT:__purecall
	DD	FLAT:__purecall
	DD	FLAT:__purecall
	DD	FLAT:__purecall
	DD	FLAT:__purecall
	DD	FLAT:__purecall
	DD	FLAT:__purecall
	DD	FLAT:__purecall
	DD	FLAT:__purecall
	DD	FLAT:__purecall
	DD	FLAT:__purecall
	DD	FLAT:__purecall
	DD	FLAT:__purecall
	DD	FLAT:__purecall
; Function compile flags: /Ogtpy
CONST	ENDS
;	COMDAT ??0ICvCivilizationInfo1@@QAE@XZ
_TEXT	SEGMENT
??0ICvCivilizationInfo1@@QAE@XZ PROC			; ICvCivilizationInfo1::ICvCivilizationInfo1, COMDAT
; _this$ = ecx
	mov	eax, ecx
	mov	DWORD PTR [eax], OFFSET ??_7ICvCivilizationInfo1@@6B@
	ret	0
??0ICvCivilizationInfo1@@QAE@XZ ENDP			; ICvCivilizationInfo1::ICvCivilizationInfo1
; Function compile flags: /Ogtpy
; File c:\users\enormousapplepie\documents\github\lekmod\lekmod_dll\cvgamecoredll_expansion2\cvdllcivilizationinfo.cpp
_TEXT	ENDS
;	COMDAT ?QueryInterface@CvDllCivilizationInfo@@UAGPAXU_GUID@@@Z
_TEXT	SEGMENT
$T218612 = -16						; size = 16
$T218610 = -16						; size = 16
_this$ = 8						; size = 4
_guidInterface$ = 12					; size = 16
?QueryInterface@CvDllCivilizationInfo@@UAGPAXU_GUID@@@Z PROC ; CvDllCivilizationInfo::QueryInterface, COMDAT

; 28   : {

	sub	esp, 16					; 00000010H

; 29   : 	if(guidInterface == ICvUnknown::GetInterfaceId() ||
; 30   : 	        guidInterface == ICvCivilizationInfo1::GetInterfaceId())

	mov	ecx, DWORD PTR _guidICvUnknown+4
	mov	edx, DWORD PTR _guidICvUnknown+8
	mov	eax, DWORD PTR _guidICvUnknown
	mov	DWORD PTR $T218610[esp+20], ecx
	lea	ecx, DWORD PTR $T218610[esp+16]
	mov	DWORD PTR $T218610[esp+24], edx
	mov	DWORD PTR $T218610[esp+16], eax
	mov	eax, DWORD PTR _guidICvUnknown+12
	push	ecx
	lea	edx, DWORD PTR _guidInterface$[esp+16]
	push	edx
	mov	DWORD PTR $T218610[esp+36], eax
	call	_IsEqualGUID
	add	esp, 8
	test	eax, eax
	jne	SHORT $LN1@QueryInter
	mov	ecx, DWORD PTR _guidICvCivilizationInfo1+4
	mov	edx, DWORD PTR _guidICvCivilizationInfo1+8
	mov	eax, DWORD PTR _guidICvCivilizationInfo1
	mov	DWORD PTR $T218612[esp+20], ecx
	lea	ecx, DWORD PTR $T218612[esp+16]
	mov	DWORD PTR $T218612[esp+24], edx
	mov	DWORD PTR $T218612[esp+16], eax
	mov	eax, DWORD PTR _guidICvCivilizationInfo1+12
	push	ecx
	lea	edx, DWORD PTR _guidInterface$[esp+16]
	push	edx
	mov	DWORD PTR $T218612[esp+36], eax
	call	_IsEqualGUID
	add	esp, 8
	test	eax, eax
	jne	SHORT $LN1@QueryInter

; 33   : 		return this;
; 34   : 	}
; 35   : 
; 36   : 	return NULL;
; 37   : }

	add	esp, 16					; 00000010H
	ret	20					; 00000014H
$LN1@QueryInter:

; 31   : 	{
; 32   : 		IncrementReference();

	mov	eax, DWORD PTR _this$[esp+12]
	inc	DWORD PTR [eax+4]

; 33   : 		return this;
; 34   : 	}
; 35   : 
; 36   : 	return NULL;
; 37   : }

	add	esp, 16					; 00000010H
	ret	20					; 00000014H
?QueryInterface@CvDllCivilizationInfo@@UAGPAXU_GUID@@@Z ENDP ; CvDllCivilizationInfo::QueryInterface
_TEXT	ENDS
PUBLIC	??_GCvDllCivilizationInfo@@QAEPAXI@Z		; CvDllCivilizationInfo::`scalar deleting destructor'
; Function compile flags: /Ogtpy
;	COMDAT ??_GCvDllCivilizationInfo@@QAEPAXI@Z
_TEXT	SEGMENT
___flags$ = 8						; size = 4
??_GCvDllCivilizationInfo@@QAEPAXI@Z PROC		; CvDllCivilizationInfo::`scalar deleting destructor', COMDAT
; _this$ = ecx
	test	BYTE PTR ___flags$[esp-4], 1
	push	esi
	mov	esi, ecx
	mov	DWORD PTR [esi], OFFSET ??_7CvDllCivilizationInfo@@6B@
	je	SHORT $LN8@scalar
	push	esi
	call	?Free@CvDllGameContext@@SAXPAX@Z	; CvDllGameContext::Free
	add	esp, 4
$LN8@scalar:
	mov	eax, esi
	pop	esi
	ret	4
??_GCvDllCivilizationInfo@@QAEPAXI@Z ENDP		; CvDllCivilizationInfo::`scalar deleting destructor'
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?GetType@CvDllCivilizationInfo@@UAGPBDXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetType@CvDllCivilizationInfo@@UAGPBDXZ PROC		; CvDllCivilizationInfo::GetType, COMDAT

; 86   : 	return m_pCivilizationInfo->GetType();

	mov	eax, DWORD PTR _this$[esp-4]
	mov	eax, DWORD PTR [eax+8]
	lea	ecx, DWORD PTR [eax+176]
	call	DWORD PTR __imp_?c_str@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QBEPBDXZ

; 87   : }

	ret	4
?GetType@CvDllCivilizationInfo@@UAGPBDXZ ENDP		; CvDllCivilizationInfo::GetType
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?GetDescription@CvDllCivilizationInfo@@UAGPBDXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?GetDescription@CvDllCivilizationInfo@@UAGPBDXZ PROC	; CvDllCivilizationInfo::GetDescription, COMDAT

; 91   : 	return m_pCivilizationInfo->GetDescription();

	mov	eax, DWORD PTR _this$[esp-4]
	mov	eax, DWORD PTR [eax+8]
	lea	ecx, DWORD PTR [eax+36]
	call	DWORD PTR __imp_?c_str@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QBEPBDXZ

; 92   : }

	ret	4
?GetDescription@CvDllCivilizationInfo@@UAGPBDXZ ENDP	; CvDllCivilizationInfo::GetDescription
_TEXT	ENDS
PUBLIC	??0CvDllCivilizationInfo@@QAE@PAVCvCivilizationInfo@@@Z ; CvDllCivilizationInfo::CvDllCivilizationInfo
; Function compile flags: /Ogtpy
;	COMDAT ??0CvDllCivilizationInfo@@QAE@PAVCvCivilizationInfo@@@Z
_TEXT	SEGMENT
_pCivilizationInfo$ = 8					; size = 4
??0CvDllCivilizationInfo@@QAE@PAVCvCivilizationInfo@@@Z PROC ; CvDllCivilizationInfo::CvDllCivilizationInfo, COMDAT
; _this$ = ecx

; 19   : {

	mov	eax, ecx
	mov	ecx, DWORD PTR _pCivilizationInfo$[esp-4]
	mov	DWORD PTR [eax], OFFSET ??_7CvDllCivilizationInfo@@6B@
	mov	DWORD PTR [eax+4], 1
	mov	DWORD PTR [eax+8], ecx

; 20   : 	FAssertMsg(pCivilizationInfo != NULL, "SHOULD NOT HAPPEN");
; 21   : }

	ret	4
??0CvDllCivilizationInfo@@QAE@PAVCvCivilizationInfo@@@Z ENDP ; CvDllCivilizationInfo::CvDllCivilizationInfo
_TEXT	ENDS
PUBLIC	?DecrementReference@CvDllCivilizationInfo@@QAEIXZ ; CvDllCivilizationInfo::DecrementReference
; Function compile flags: /Ogtpy
;	COMDAT ?DecrementReference@CvDllCivilizationInfo@@QAEIXZ
_TEXT	SEGMENT
?DecrementReference@CvDllCivilizationInfo@@QAEIXZ PROC	; CvDllCivilizationInfo::DecrementReference, COMDAT
; _this$ = ecx

; 47   : 	if(m_uiRefCount == 1)

	mov	eax, DWORD PTR [ecx+4]
	cmp	eax, 1
	jne	SHORT $LN2@DecrementR

; 48   : 	{
; 49   : 		delete this;

	push	ecx
	mov	DWORD PTR [ecx], OFFSET ??_7CvDllCivilizationInfo@@6B@
	call	?Free@CvDllGameContext@@SAXPAX@Z	; CvDllGameContext::Free
	add	esp, 4

; 50   : 		return 0;

	xor	eax, eax

; 55   : 		return m_uiRefCount;
; 56   : 	}
; 57   : }

	ret	0
$LN2@DecrementR:

; 51   : 	}
; 52   : 	else
; 53   : 	{
; 54   : 		--m_uiRefCount;

	dec	eax
	mov	DWORD PTR [ecx+4], eax

; 55   : 		return m_uiRefCount;
; 56   : 	}
; 57   : }

	ret	0
?DecrementReference@CvDllCivilizationInfo@@QAEIXZ ENDP	; CvDllCivilizationInfo::DecrementReference
; Function compile flags: /Ogtpy
_TEXT	ENDS
;	COMDAT ?Destroy@CvDllCivilizationInfo@@EAGXXZ
_TEXT	SEGMENT
_this$ = 8						; size = 4
?Destroy@CvDllCivilizationInfo@@EAGXXZ PROC		; CvDllCivilizationInfo::Destroy, COMDAT

; 66   : 	DecrementReference();

	mov	eax, DWORD PTR _this$[esp-4]
	mov	ecx, DWORD PTR [eax+4]
	cmp	ecx, 1
	jne	SHORT $LN4@Destroy
	push	eax
	mov	DWORD PTR [eax], OFFSET ??_7CvDllCivilizationInfo@@6B@
	call	?Free@CvDllGameContext@@SAXPAX@Z	; CvDllGameContext::Free
	add	esp, 4

; 67   : }

	ret	4

; 66   : 	DecrementReference();

$LN4@Destroy:
	dec	ecx
	mov	DWORD PTR [eax+4], ecx

; 67   : }

	ret	4
?Destroy@CvDllCivilizationInfo@@EAGXXZ ENDP		; CvDllCivilizationInfo::Destroy
_TEXT	ENDS
END
